---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: petclinic
  name: petclinic
  namespace: petclinic
spec:
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
  selector:
    io.kompose.service: petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: petclinic
  name: petclinic
  namespace: petclinic
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      io.kompose.service: petclinic
  template:
    metadata:
      labels:
        io.kompose.service: petclinic
        app: petclinic
    spec:
      containers:
        - env:
            - name: TOTO
              value: "true"
          image: slibaros/sre-team-b:latest
          name: petclinic
          ports:
            - containerPort: 8181
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: petclinic
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: petclinic
              port:
                number: 8181
