global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheusMC'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9091']
  - job_name: 'nodeExporter-MC'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'nodeExporter-Prod'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.126.213.216:9100']
  - job_name: 'nodeExporter-Jenkins'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.126.213.252:9100']
  - job_name: 'MySQLExporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.126.213.245:9104']

